### ISSUE TITLE
maybe relax password requirements

### ISSUE THREAD

**Issue by epogrebnyak** [hawshemi/blockchain#8]
nice work! have you thought of relaxing passwpord requirements? 

it took me several attemps to make a valid password - each time I thought about - the symbols requirements do not add to password security - it is the length of a password that does

given your focus is to demostrate the blockchain - accepting any password even like `zzz` would be a fair bet and make you users happier.

**Comment by hawshemi** [comment]
Thanks for your feedback.
As this project was for the CS50 Final project, the password requirements were from that project's necessities. but you are right after that project it should be simpler.

**Comment by epogrebnyak** [comment]
As a side note - maybe this could get a mention in a CS50 class: 

[![](https://imgs.xkcd.com/comics/password_strength.png)](https://xkcd.com/936/)

Feel free to close an issue at your discretion.

**Comment by hawshemi** [comment]
Updated. https://github.com/hawshemi/Blockchain/commit/82a20f97fe7665b76de2b179ea055dc52ef03337

Thanks.
